"use client";

import React from "react";
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerFooter,
    DrawerClose,
} from "@/components/ui/drawer";
import { Invoice } from "@/types/api";
import { PDFViewer, PDFDownloadLink } from "@react-pdf/renderer";
import { InvoicePDF } from "./InvoicePDF";
import { Download, Loader2, X } from "lucide-react";
import { Button } from "@/components/ui/button";

interface InvoiceViewModalProps {
    isOpen: boolean;
    onClose: () => void;
    invoice: Invoice | null;
}

export function InvoiceViewModal({ isOpen, onClose, invoice }: InvoiceViewModalProps) {
    if (!invoice) return null;

    return (
        <Drawer open={isOpen} onOpenChange={onClose} direction="right">
            <DrawerContent className="h-full flex flex-col sm:max-w-4xl">
                <DrawerHeader className="border-b px-6 py-4 flex flex-row items-center justify-between">
                    <div>
                        <DrawerTitle className="text-xl font-bold">
                            Invoice: {invoice.invoiceNumber}
                        </DrawerTitle>
                        <p className="text-xs text-muted-foreground mt-0.5">
                            PDF Preview & Download
                        </p>
                    </div>
                    <DrawerClose asChild>
                        <Button variant="ghost" size="icon" className="rounded-full h-8 w-8">
                            <X className="w-4 h-4" />
                        </Button>
                    </DrawerClose>
                </DrawerHeader>

                <div className="flex-1 bg-muted/10 p-4 md:p-6 overflow-hidden">
                    <div className="h-full w-full rounded-xl overflow-hidden shadow-2xl border border-border/50 bg-white dark:bg-zinc-900 ring-1 ring-black/5">
                        <PDFViewer
                            width="100%"
                            height="100%"
                            className="border-0 bg-transparent"
                            showToolbar={false}
                        >
                            <InvoicePDF invoice={invoice} />
                        </PDFViewer>
                    </div>
                </div>

                <DrawerFooter className="border-t bg-background/80 backdrop-blur-md px-6 py-4 flex-row justify-between items-center sm:gap-4">
                    <div className="hidden sm:block">
                        <p className="text-[10px] uppercase tracking-wider font-semibold text-muted-foreground">
                            Generated by VoltERP
                        </p>
                    </div>
                    <div className="flex gap-3 w-full sm:w-auto">
                        <DrawerClose asChild>
                            <Button variant="outline" className="flex-1 sm:flex-none">Cancel</Button>
                        </DrawerClose>
                        <PDFDownloadLink
                            document={<InvoicePDF invoice={invoice} />}
                            fileName={`Invoice_${invoice.invoiceNumber.replace(/\//g, '-')}.pdf`}
                            className="flex-1 sm:flex-none"
                        >
                            {({ loading }) => (
                                <Button className="w-full gap-2 shadow-sm" disabled={loading}>
                                    {loading ? (
                                        <Loader2 className="w-4 h-4 animate-spin" />
                                    ) : (
                                        <Download className="w-4 h-4" />
                                    )}
                                    Download PDF
                                </Button>
                            )}
                        </PDFDownloadLink>
                    </div>
                </DrawerFooter>
            </DrawerContent>
        </Drawer>
    );
}
